[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://www.google-analytics.com;
    img-src 'self' 'unsafe-inline' https://www.google.com;
    media-src 'self' https://www.youtube.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    script-src 'self' 'unsafe-inline' https://typeform.com connect.facebook.net https://www.google-analytics.com;
    script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com;
    frame-src 'self' https://app.frame.io https://www.youtube.com/ https://vimeo.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"